
def insertionSort(list):
	#TODO: IMPLEMENT THIS METHOD

def partition(list, i, j):
	#TODO: PARTITION FOR QUICKSORT

def quickSortHelper(list, i, j):
	#TODO: VERSION OF QUICKSORT THAT ACCEPTS ARRAY INDICES


def quickSort(list):
	#TODO: IMPLEMENT QUICKSORT (THIS ONE IS THE ONE CALLED BY THE DRIVER) 
